// User Roles
const USER_ROLES = {
  ADMIN: 'ADMIN',
  ACCOUNTANT: 'ACCOUNTANT',
  MANAGER: 'MANAGER',
  VIEWER: 'VIEWER',
};

// Ship Status
const SHIP_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  MAINTENANCE: 'MAINTENANCE',
};

// Income Types
const INCOME_TYPES = {
  SALES: 'SALES',
  DELIVERY_ORDER: 'DELIVERY_ORDER',
};

// Expense Categories
const EXPENSE_CATEGORIES = {
  MARINE_BILLS: 'MARINE_BILLS',
  SALARY: 'SALARY',
  MAINTENANCE_REPAIR: 'MAINTENANCE_REPAIR',
  FUEL_COST: 'FUEL_COST',
  FOOD_GROCERY: 'FOOD_GROCERY',
  PORT_CASH: 'PORT_CASH',
  ZMA_BILLS: 'ZMA_BILLS',
  LOAN_REPAYMENT: 'LOAN_REPAYMENT',
  ADMINISTRATION_COST: 'ADMINISTRATION_COST',
  OTHER_COST: 'OTHER_COST',
};

// Payment Methods
const PAYMENT_METHODS = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHEQUE: 'CHEQUE',
};

// Loan Status
const LOAN_STATUS = {
  ACTIVE: 'ACTIVE',
  PAID_OFF: 'PAID_OFF',
};

// HTTP Status Codes
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  SERVER_ERROR: 500,
};

// Pagination
const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

// JWT
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || '7d';

// File Upload
const MAX_FILE_SIZE = parseInt(process.env.MAX_FILE_SIZE || '5242880', 10); // 5MB default
const ALLOWED_FILE_TYPES = ['image/jpeg', 'image/png', 'application/pdf'];

module.exports = {
  USER_ROLES,
  SHIP_STATUS,
  INCOME_TYPES,
  EXPENSE_CATEGORIES,
  PAYMENT_METHODS,
  LOAN_STATUS,
  HTTP_STATUS,
  PAGINATION,
  JWT_EXPIRES_IN,
  MAX_FILE_SIZE,
  ALLOWED_FILE_TYPES,
};
